-- | Embedded C runtime source for the native backend.
--
-- The runtime is compiled as a separate C file and linked with the
-- generated assembly. This module provides the runtime source as a
-- Haskell string constant.
module Stele.Runtime
  ( runtimeSource
  ) where

-- | The C runtime source code for linking with native-compiled programs.
runtimeSource :: String
runtimeSource = unlines
  [ "#include <stdio.h>"
  , "#include <stdlib.h>"
  , "#include <string.h>"
  , "#include <stdint.h>"
  , "#include <unistd.h>"
  , "#include <sys/wait.h>"
  , ""
  , "typedef enum { TAG_INT, TAG_STR, TAG_RECORD, TAG_VOID, TAG_CLOSURE } Tag;"
  , ""
  , "typedef struct Field {"
  , "    const char* name;"
  , "    struct Value* value;"
  , "} Field;"
  , ""
  , "typedef struct Value {"
  , "    Tag tag;"
  , "    int refcount;"
  , "    union {"
  , "        int64_t int_val;"
  , "        char* str_val;"
  , "        struct { int num_fields; Field* fields; } record;"
  , "        struct { struct Value* (*fn_ptr)(struct Value*); struct Value* env; } closure;"
  , "    };"
  , "} Value;"
  , ""
  , "void rc_release(Value* v);"
  , ""
  , "static void stele_runtime_null(const char* where) {"
  , "    fprintf(stderr, \"stele: null value in %s\\n\", where);"
  , "    exit(1);"
  , "}"
  , ""
  , "static void* stele_malloc(size_t size) {"
  , "    void* p = malloc(size);"
  , "    if (!p) { fprintf(stderr, \"stele: out of memory (%zu bytes)\\n\", size); abort(); }"
  , "    return p;"
  , "}"
  , ""
  , "static char* stele_strdup(const char* s) {"
  , "    char* p = strdup(s);"
  , "    if (!p) { fprintf(stderr, \"stele: out of memory (strdup)\\n\"); abort(); }"
  , "    return p;"
  , "}"
  , ""
  , "void rc_retain(Value* v) {"
  , "    if (!v) return;"
  , "    v->refcount++;"
  , "}"
  , ""
  , "Value* make_int(int64_t n) {"
  , "    Value* v = (Value*)stele_malloc(sizeof(Value));"
  , "    v->tag = TAG_INT;"
  , "    v->refcount = 1;"
  , "    v->int_val = n;"
  , "    return v;"
  , "}"
  , ""
  , "Value* make_str(const char* s) {"
  , "    Value* v = (Value*)stele_malloc(sizeof(Value));"
  , "    v->tag = TAG_STR;"
  , "    v->refcount = 1;"
  , "    v->str_val = stele_strdup(s);"
  , "    return v;"
  , "}"
  , ""
  , "Value* make_void(void) {"
  , "    Value* v = (Value*)stele_malloc(sizeof(Value));"
  , "    v->tag = TAG_VOID;"
  , "    v->refcount = 1;"
  , "    return v;"
  , "}"
  , ""
  , "Value* make_record_with_fields(int n, const char** names, Value** values) {"
  , "    Value* v = (Value*)stele_malloc(sizeof(Value));"
  , "    v->tag = TAG_RECORD;"
  , "    v->refcount = 1;"
  , "    v->record.num_fields = n;"
  , "    v->record.fields = (Field*)stele_malloc(sizeof(Field) * n);"
  , "    for (int i = 0; i < n; i++) {"
  , "        v->record.fields[i].name = names[i];"
  , "        v->record.fields[i].value = values[i];"
  , "    }"
  , "    return v;"
  , "}"
  , ""
  , "Value* make_closure(Value* (*fn_ptr)(Value*), Value* env) {"
  , "    Value* v = (Value*)stele_malloc(sizeof(Value));"
  , "    v->tag = TAG_CLOSURE;"
  , "    v->refcount = 1;"
  , "    v->closure.fn_ptr = fn_ptr;"
  , "    v->closure.env = env;"
  , "    if (env) rc_retain(env);"
  , "    return v;"
  , "}"
  , ""
  , "Value* stele_call_closure(Value* clos, Value* arg) {"
  , "    if (!clos || clos->tag != TAG_CLOSURE) {"
  , "        fprintf(stderr, \"stele: attempt to call non-closure value\\n\");"
  , "        exit(1);"
  , "    }"
  , "    Value* env = clos->closure.env;"
  , "    if (env && env->tag == TAG_RECORD && arg && arg->tag == TAG_RECORD) {"
  , "        int total = arg->record.num_fields + env->record.num_fields;"
  , "        Value* merged = (Value*)stele_malloc(sizeof(Value));"
  , "        merged->tag = TAG_RECORD;"
  , "        merged->refcount = 1;"
  , "        merged->record.num_fields = total;"
  , "        merged->record.fields = (Field*)stele_malloc(sizeof(Field) * total);"
  , "        for (int i = 0; i < arg->record.num_fields; i++) {"
  , "            merged->record.fields[i] = arg->record.fields[i];"
  , "            rc_retain(arg->record.fields[i].value);"
  , "        }"
  , "        for (int i = 0; i < env->record.num_fields; i++) {"
  , "            merged->record.fields[arg->record.num_fields + i] = env->record.fields[i];"
  , "            rc_retain(env->record.fields[i].value);"
  , "        }"
  , "        Value* result = clos->closure.fn_ptr(merged);"
  , "        rc_release(merged);"
  , "        return result;"
  , "    }"
  , "    return clos->closure.fn_ptr(arg);"
  , "}"
  , ""
  , "void rc_release(Value* v) {"
  , "    Value* stack[64];"
  , "    int sp = 0;"
  , "    if (!v) return;"
  , "    stack[sp++] = v;"
  , "    while (sp > 0) {"
  , "        Value* cur = stack[--sp];"
  , "        if (!cur) continue;"
  , "        cur->refcount--;"
  , "        if (cur->refcount > 0) continue;"
  , "        switch (cur->tag) {"
  , "            case TAG_STR: free(cur->str_val); break;"
  , "            case TAG_RECORD:"
  , "                for (int i = 0; i < cur->record.num_fields; i++) {"
  , "                    Value* child = cur->record.fields[i].value;"
  , "                    if (!child) continue;"
  , "                    if (sp < 64) {"
  , "                        stack[sp++] = child;"
  , "                    } else {"
  , "                        rc_release(child);"
  , "                    }"
  , "                }"
  , "                free(cur->record.fields);"
  , "                break;"
  , "            case TAG_CLOSURE:"
  , "                if (cur->closure.env) {"
  , "                    if (sp < 64) {"
  , "                        stack[sp++] = cur->closure.env;"
  , "                    } else {"
  , "                        rc_release(cur->closure.env);"
  , "                    }"
  , "                }"
  , "                break;"
  , "            default: break;"
  , "        }"
  , "        free(cur);"
  , "    }"
  , "}"
  , ""
  , "Value* record_field(Value* rec, const char* name) {"
  , "    if (!rec || rec->tag != TAG_RECORD) return NULL;"
  , "    for (int i = 0; i < rec->record.num_fields; i++) {"
  , "        if (strcmp(rec->record.fields[i].name, name) == 0)"
  , "            return rec->record.fields[i].value;"
  , "    }"
  , "    return NULL;"
  , "}"
  , ""
  , "void stele_write(Value* v);"
  , ""
  , "int stele_value_eq(Value* a, Value* b) {"
  , "    if (a == b) return 1;"
  , "    if (!a || !b) return 0;"
  , "    if (a->tag != b->tag) return 0;"
  , "    switch (a->tag) {"
  , "        case TAG_INT: return a->int_val == b->int_val;"
  , "        case TAG_STR: return strcmp(a->str_val, b->str_val) == 0;"
  , "        case TAG_VOID: return 1;"
  , "        case TAG_RECORD:"
  , "            if (a->record.num_fields != b->record.num_fields) return 0;"
  , "            for (int i = 0; i < a->record.num_fields; i++) {"
  , "                Value* bv = record_field(b, a->record.fields[i].name);"
  , "                if (!bv) return 0;"
  , "                if (!stele_value_eq(a->record.fields[i].value, bv)) return 0;"
  , "            }"
  , "            return 1;"
  , "        case TAG_CLOSURE: return a == b;"
  , "    }"
  , "    return 0;"
  , "}"
  , ""
  , "int stele_value_neq(Value* a, Value* b) {"
  , "    return !stele_value_eq(a, b);"
  , "}"
  , ""
  , "void stele_print(Value* v) {"
  , "    if (!v) stele_runtime_null(\"print\");"
  , "    switch (v->tag) {"
  , "        case TAG_INT:    printf(\"%lld\\n\", (long long)v->int_val); break;"
  , "        case TAG_STR:    printf(\"%s\\n\", v->str_val); break;"
  , "        case TAG_VOID:   printf(\"void\\n\"); break;"
  , "        case TAG_RECORD: {"
  , "            printf(\"{| \");"
  , "            for (int i = 0; i < v->record.num_fields; i++) {"
  , "                if (i > 0) printf(\", \");"
  , "                printf(\"%s: \", v->record.fields[i].name);"
  , "                stele_write(v->record.fields[i].value);"
  , "            }"
  , "            printf(\" |}\\n\");"
  , "            break;"
  , "        }"
  , "        case TAG_CLOSURE: printf(\"<closure>\\n\"); break;"
  , "    }"
  , "}"
  , ""
  , "void stele_write(Value* v) {"
  , "    if (!v) stele_runtime_null(\"write\");"
  , "    switch (v->tag) {"
  , "        case TAG_INT:    printf(\"%lld\", (long long)v->int_val); break;"
  , "        case TAG_STR:    printf(\"%s\", v->str_val); break;"
  , "        case TAG_VOID:   printf(\"void\"); break;"
  , "        case TAG_RECORD: {"
  , "            printf(\"{| \");"
  , "            for (int i = 0; i < v->record.num_fields; i++) {"
  , "                if (i > 0) printf(\", \");"
  , "                printf(\"%s: \", v->record.fields[i].name);"
  , "                stele_write(v->record.fields[i].value);"
  , "            }"
  , "            printf(\" |}\");"
  , "            break;"
  , "        }"
  , "        case TAG_CLOSURE: printf(\"<closure>\"); break;"
  , "    }"
  , "}"
  , ""
  , "Value* runtime_readln(void) {"
  , "    char* line = NULL;"
  , "    size_t cap = 0;"
  , "    ssize_t n = getline(&line, &cap, stdin);"
  , "    if (n < 0) {"
  , "        free(line);"
  , "        return make_str(\"\");"
  , "    }"
  , "    if (n > 0 && line[n-1] == '\\n') line[n-1] = '\\0';"
  , "    Value* result = make_str(line);"
  , "    free(line);"
  , "    return result;"
  , "}"
  , ""
  , "Value* runtime_readint(void) {"
  , "    long long n = 0;"
  , "    if (scanf(\"%lld\", &n) != 1) {"
  , "        fprintf(stderr, \"stele: readint failed to read integer\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int c = getchar(); (void)c;"
  , "    return make_int((int64_t)n);"
  , "}"
  , ""
  , "void stele_match_fail(const char* msg) {"
  , "    fprintf(stderr, \"Pattern match failure in %s\\n\", msg);"
  , "    exit(1);"
  , "}"
  , ""
  , "int g_argc = 0;"
  , "char** g_argv = NULL;"
  , ""
  , "Value* fn_read(Value* arg) {"
  , "    Value* pathVal = record_field(arg, \"path\");"
  , "    if (!pathVal || pathVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele: read requires path: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    FILE* f = fopen(pathVal->str_val, \"r\");"
  , "    if (!f) {"
  , "        fprintf(stderr, \"stele: read cannot open '%s'\\n\", pathVal->str_val);"
  , "        exit(1);"
  , "    }"
  , "    fseek(f, 0, SEEK_END);"
  , "    long sz = ftell(f);"
  , "    fseek(f, 0, SEEK_SET);"
  , "    char* buf = (char*)stele_malloc(sz + 1);"
  , "    fread(buf, 1, sz, f);"
  , "    buf[sz] = '\\0';"
  , "    fclose(f);"
  , "    Value* result = make_str(buf);"
  , "    free(buf);"
  , "    return result;"
  , "}"
  , ""
  , "Value* fn_write(Value* arg) {"
  , "    Value* pathVal = record_field(arg, \"path\");"
  , "    Value* contentVal = record_field(arg, \"content\");"
  , "    if (!pathVal || pathVal->tag != TAG_STR ||"
  , "        !contentVal || contentVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele: write requires path: String, content: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    FILE* f = fopen(pathVal->str_val, \"w\");"
  , "    if (!f) {"
  , "        fprintf(stderr, \"stele: write cannot open '%s'\\n\", pathVal->str_val);"
  , "        exit(1);"
  , "    }"
  , "    fputs(contentVal->str_val, f);"
  , "    fclose(f);"
  , "    return make_void();"
  , "}"
  , ""
  , "Value* fn_argc(Value* arg) {"
  , "    (void)arg;"
  , "    return make_int((int64_t)g_argc);"
  , "}"
  , ""
  , "Value* fn_argv(Value* arg) {"
  , "    Value* nVal = record_field(arg, \"n\");"
  , "    if (!nVal || nVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele: argv requires n: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int idx = (int)nVal->int_val;"
  , "    if (idx < 0 || idx >= g_argc) {"
  , "        fprintf(stderr, \"stele: argv index %d out of bounds (argc=%d)\\n\", idx, g_argc);"
  , "        exit(1);"
  , "    }"
  , "    return make_str(g_argv[idx]);"
  , "}"
  , ""
  , "Value* fn_sh(Value* arg) {"
  , "    Value* cmdVal = record_field(arg, \"command\");"
  , "    if (!cmdVal || cmdVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele: sh requires command: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int rc = system(cmdVal->str_val);"
  , "    return make_int((int64_t)rc);"
  , "}"
  , ""
  , "Value* fn_terminate(Value* arg) {"
  , "    Value* codeVal = record_field(arg, \"code\");"
  , "    if (!codeVal || codeVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele: terminate requires code: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    exit((int)codeVal->int_val);"
  , "}"
  , ""
  , "Value* fn_spawn(Value* arg) {"
  , "    Value* cmdVal = record_field(arg, \"command\");"
  , "    if (!cmdVal || cmdVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele: spawn requires command: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    pid_t pid = fork();"
  , "    if (pid < 0) {"
  , "        fprintf(stderr, \"stele: spawn failed\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (pid == 0) {"
  , "        execl(\"/bin/sh\", \"sh\", \"-c\", cmdVal->str_val, (char*)NULL);"
  , "        _exit(127);"
  , "    }"
  , "    return make_int((int64_t)pid);"
  , "}"
  , ""
  , "Value* fn_await(Value* arg) {"
  , "    Value* pidVal = record_field(arg, \"pid\");"
  , "    if (!pidVal || pidVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele: await requires pid: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int status = 0;"
  , "    pid_t r = waitpid((pid_t)pidVal->int_val, &status, 0);"
  , "    if (r < 0) {"
  , "        fprintf(stderr, \"stele: await failed for pid %lld\\n\", (long long)pidVal->int_val);"
  , "        exit(1);"
  , "    }"
  , "    if (WIFEXITED(status)) {"
  , "        return make_int((int64_t)WEXITSTATUS(status));"
  , "    }"
  , "    if (WIFSIGNALED(status)) {"
  , "        return make_int((int64_t)(128 + WTERMSIG(status)));"
  , "    }"
  , "    return make_int((int64_t)status);"
  , "}"
  , ""
  , "Value* fn_sleep_ms(Value* arg) {"
  , "    Value* msVal = record_field(arg, \"ms\");"
  , "    if (!msVal || msVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele: sleep_ms requires ms: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int64_t ms = msVal->int_val;"
  , "    if (ms < 0) ms = 0;"
  , "    usleep((useconds_t)(ms * 1000));"
  , "    return make_void();"
  , "}"
  , ""
  , "Value* fn_strlen(Value* arg) {"
  , "    Value* sVal = record_field(arg, \"s\");"
  , "    if (!sVal || sVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: strlen requires s: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    return make_int((int64_t)strlen(sVal->str_val));"
  , "}"
  , ""
  , "Value* fn_char_at(Value* arg) {"
  , "    Value* sVal = record_field(arg, \"s\");"
  , "    Value* nVal = record_field(arg, \"n\");"
  , "    if (!sVal || sVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: char_at requires s: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (!nVal || nVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele runtime bug: char_at requires n: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int64_t idx = nVal->int_val;"
  , "    int64_t len = (int64_t)strlen(sVal->str_val);"
  , "    if (idx < 0 || idx >= len) return make_int(-1);"
  , "    return make_int((int64_t)(unsigned char)sVal->str_val[idx]);"
  , "}"
  , ""
  , "Value* fn_substr(Value* arg) {"
  , "    Value* sVal = record_field(arg, \"s\");"
  , "    Value* startVal = record_field(arg, \"start\");"
  , "    Value* lenVal = record_field(arg, \"len\");"
  , "    if (!sVal || sVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: substr requires s: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (!startVal || startVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele runtime bug: substr requires start: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (!lenVal || lenVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele runtime bug: substr requires len: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int64_t slen = (int64_t)strlen(sVal->str_val);"
  , "    int64_t start = startVal->int_val;"
  , "    int64_t rlen = lenVal->int_val;"
  , "    if (start < 0) start = 0;"
  , "    if (start >= slen || rlen <= 0) return make_str(\"\");"
  , "    if (start + rlen > slen) rlen = slen - start;"
  , "    char* buf = (char*)stele_malloc(rlen + 1);"
  , "    memcpy(buf, sVal->str_val + start, rlen);"
  , "    buf[rlen] = '\\0';"
  , "    Value* result = make_str(buf);"
  , "    free(buf);"
  , "    return result;"
  , "}"
  , ""
  , "Value* fn_concat(Value* arg) {"
  , "    Value* aVal = record_field(arg, \"a\");"
  , "    Value* bVal = record_field(arg, \"b\");"
  , "    if (!aVal || aVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: concat requires a: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (!bVal || bVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: concat requires b: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    size_t la = strlen(aVal->str_val);"
  , "    size_t lb = strlen(bVal->str_val);"
  , "    char* buf = (char*)stele_malloc(la + lb + 1);"
  , "    memcpy(buf, aVal->str_val, la);"
  , "    memcpy(buf + la, bVal->str_val, lb);"
  , "    buf[la + lb] = '\\0';"
  , "    Value* result = make_str(buf);"
  , "    free(buf);"
  , "    return result;"
  , "}"
  , ""
  , "Value* fn_int_to_str(Value* arg) {"
  , "    Value* nVal = record_field(arg, \"n\");"
  , "    if (!nVal || nVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele runtime bug: int_to_str requires n: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    char buf[32];"
  , "    snprintf(buf, sizeof(buf), \"%lld\", (long long)nVal->int_val);"
  , "    return make_str(buf);"
  , "}"
  , ""
  , "Value* fn_char_of_int(Value* arg) {"
  , "    Value* nVal = record_field(arg, \"n\");"
  , "    if (!nVal || nVal->tag != TAG_INT) {"
  , "        fprintf(stderr, \"stele runtime bug: char_of_int requires n: Int\\n\");"
  , "        exit(1);"
  , "    }"
  , "    char buf[2] = { (char)nVal->int_val, '\\0' };"
  , "    return make_str(buf);"
  , "}"
  , ""
  , "Value* fn_strcmp(Value* arg) {"
  , "    Value* aVal = record_field(arg, \"a\");"
  , "    Value* bVal = record_field(arg, \"b\");"
  , "    if (!aVal || aVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: strcmp requires a: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    if (!bVal || bVal->tag != TAG_STR) {"
  , "        fprintf(stderr, \"stele runtime bug: strcmp requires b: String\\n\");"
  , "        exit(1);"
  , "    }"
  , "    int r = strcmp(aVal->str_val, bVal->str_val);"
  , "    return make_int((int64_t)(r < 0 ? -1 : (r > 0 ? 1 : 0)));"
  , "}"
  , ""
  , "/* ── checked arithmetic ──────────────────────────────────────── */"
  , ""
  , "Value* checked_add(Value* a, Value* b) {"
  , "    int64_t x = a->int_val, y = b->int_val, r;"
  , "    if (__builtin_add_overflow(x, y, &r)) {"
  , "        fprintf(stderr, \"stele runtime error: integer overflow in addition\\n\");"
  , "        abort();"
  , "    }"
  , "    return make_int(r);"
  , "}"
  , ""
  , "Value* checked_sub(Value* a, Value* b) {"
  , "    int64_t x = a->int_val, y = b->int_val, r;"
  , "    if (__builtin_sub_overflow(x, y, &r)) {"
  , "        fprintf(stderr, \"stele runtime error: integer overflow in subtraction\\n\");"
  , "        abort();"
  , "    }"
  , "    return make_int(r);"
  , "}"
  , ""
  , "Value* checked_mul(Value* a, Value* b) {"
  , "    int64_t x = a->int_val, y = b->int_val, r;"
  , "    if (__builtin_mul_overflow(x, y, &r)) {"
  , "        fprintf(stderr, \"stele runtime error: integer overflow in multiplication\\n\");"
  , "        abort();"
  , "    }"
  , "    return make_int(r);"
  , "}"
  ]
