cabal-version:   3.14
name:            stele
version:         0.1.0.0
license:         MIT
author:          Samuel Schlesinger
maintainer:      sgschlesinger@gmail.com
build-type:      Simple
extra-doc-files: CHANGELOG.md

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:
        Stele.PEG
        Stele.AST
        Stele.Grammar
        Stele.Types
        Stele.IR
        Stele.Lower
        Stele.EmitC
        Stele.EmitAArch64
        Stele.EmitX86_64
        Stele.Runtime
    build-depends:
        base       ^>=4.18.3.0,
        containers >= 0.6,
        array      >= 0.5,
        transformers >= 0.5
    hs-source-dirs:   src
    default-language: Haskell2010

executable stele
    import:           warnings
    main-is:          Main.hs
    build-depends:
        base       ^>=4.18.3.0,
        stele,
        process    >= 1.6
    hs-source-dirs:   app
    default-language: Haskell2010
